# Generated by Django 3.1.14 on 2025-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='Appeared_at',
            field=models.DateTimeField(default='1990-01-01 11:11'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='Disapeared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
