# Generated by Django 3.1.14 on 2025-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
