# Generated by Django 3.1.14 on 2025-06-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20250615_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Appeared_at',
            field=models.DateTimeField(default='1990-01-01 11:11'),
        ),
    ]
