# Generated by Django 3.1.14 on 2025-06-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20250622_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Healt',
            new_name='Health',
        ),
    ]
