# Generated by Django 3.1.14 on 2025-07-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20250629_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='Ru_Name',
            field=models.CharField(default='Покемон', max_length=200),
        ),
    ]
