# Generated by Django 3.1.14 on 2025-07-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20250713_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='Name',
            new_name='Title_en',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='Name_Ru',
            new_name='Title_ru',
        ),
    ]
