# Generated by Django 3.1.14 on 2025-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20250713_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='Description',
            field=models.CharField(default='Описание покемона', max_length=400),
        ),
    ]
